### ISSUE TITLE
SPV36 needs a new name

### ISSUE THREAD

**Issue by indolering** [hlandau/ncdocs#1]
The problem is that we are planning on increasing the number of blocks to match ~13 months for domains.  We also anticipate multi-year renewals for ID and other namespaces.  So, SPV-C for SPV-Current?

**Comment by JeremyRand** [comment]
I am not aware of a consensus on changing renewal length based on namespace.  I am fine with using -C instead of 36.

**Comment by indolering** [comment]
@JeremyRand There is no concencus on that yet, but we will def. be changing the renewal period and the difficulty adjustment algorithm.  That's what Domob was working on with his optimal control theory....

**Comment by JeremyRand** [comment]
Renewal period, yes.  My understanding was that Daniel's difficulty adjustment stuff was (at the moment) strictly theoretical, and there were no immediate plans to add it to Namecoin.

**Comment by indolering** [comment]
@JeremyRand yes, I was under the (incorrect) impression that it was much farther along that it actually was.  Working on getting funding for that now.

**Comment by indolering** [comment]
Fixed stateofnamecoin.md in https://github.com/hlandau/ncdocs/commit/a6ed28a28381af42d675fcd149c98deae6f28c11, nctypes-intro.md intro waiting on https://github.com/hlandau/ncdocs/pull/4, blogpost waiting on https://github.com/hlandau/ncdocs/pull/3.

**Comment by indolering** [comment]
Fixed.
