### ISSUE TITLE
alias is safer than translate

### ISSUE THREAD

**Issue by JeremyRand** [hlandau/ncdocs#11]
Regarding the warning added in https://github.com/hlandau/ncdocs/commit/a999cc28ea5504952c7a39224a3729db5009687a , I think it is good, but we should also mention that translate is _much_ worse than alias, because with alias, you can at least only delegate an IP address but keep the TLS record (which is more important) in Namecoin.  translate prevents _any_ blockchain-based security on the domain.

**Comment by indolering** [comment]
I'm fine with a warning.

**Comment by indolering** [comment]
I don't think anyone would object to your change so I'm going to close this since we are trying to clean up this repo.

**Comment by JeremyRand** [comment]
I would like this migrated to the new repo.  I will do this myself soon; until then I'm reopening as a reminder to myself to deal with it.

**Comment by hlandau** [comment]
Warning added. This issue has been resolved.
