### ISSUE TITLE
Get Daniel's feedback on import

### ISSUE THREAD

**Issue by JeremyRand** [hlandau/ncdocs#13]
I'd like to get Daniel's feedback on import before finalizing the d/ spec.

**Comment by indolering** [comment]
We first need to submit this for Draft status at the IFA repo, that way we capture the feedback in a single place.

@JeremyRand okay to close?

**Comment by JeremyRand** [comment]
Okay, I started a ticket at https://github.com/ifa-wg/proposals/issues/4 .  If that is acceptable, feel free to close this ticket.
