### ISSUE TITLE
Get Ryan's feedback on TLS

### ISSUE THREAD

**Issue by JeremyRand** [hlandau/ncdocs#14]
Ryan has requested time to give feedback on the "tls" field spec in d/.  We should wait for his feedback before finalizing.

**Comment by indolering** [comment]
We first need to submit this for Draft status at the IFA repo, that way we capture the feedback in a single place.

@JeremyRand okay to close?

**Comment by indolering** [comment]
Migrated to IFA repo: https://github.com/ifa-wg/proposals/issues/5
