### ISSUE TITLE
Multiple .onion or .i2p addresses

### ISSUE THREAD

**Issue by JeremyRand** [hlandau/ncdocs#7]
We reached consensus a long time ago that we would change the spec to allow a list of addresses for the "tor" and "i2p" fields of d/, as an alternative to a single address.  This would have the same role as the load balancing for "ip" and "ip6".  See https://forum.namecoin.info/viewtopic.php?f=5&t=546 .  Can this change be merged into the spec draft here?

**Comment by hlandau** [comment]
Fixed.
