### ISSUE TITLE
DN: Allow import to limit types imported

### ISSUE THREAD

**Issue by hlandau** [hlandau/ncdocs#9]
Jeremy Rand posted:

Also, I would like to see an optional third argument to an import, which consists of an array of the fields being imported. E.g. ["ip", "ip6"] would restrict the import to just those two fields (after applying the "import" fields in the imported name) rather than also importing things like TLS fingerprints. A value of ["*"] would be the default, and would import everything.

**Comment by indolering** [comment]
Migrated to new repo:

https://github.com/ifa-wg/proposals/issues/6
